# Generated by Django 5.2.3 on 2025-07-07 06:53

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Короткое название (СМУ, Контур, Инженеринг)', max_length=100, verbose_name='Сокращенное наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='OrganizationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Локация организации',
                'verbose_name_plural': 'Локации организаций',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Обязательное поле', max_length=254, unique=True, verbose_name='Почта')),
                ('username', models.CharField(help_text='Обязательное поле. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, verbose_name='Логин')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, help_text='Статус активности профиля', verbose_name='Активен')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.department', verbose_name='Подразделение')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.organizationlocation', verbose_name='Локация организации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подачи')),
                ('date_start', models.DateField(db_index=True, verbose_name='Дата начала работ')),
                ('date_end', models.DateField(db_index=True, verbose_name='Дата окончания работ')),
                ('time_start', models.TimeField(verbose_name='Время начала работ')),
                ('time_end', models.TimeField(verbose_name='Время окончания работ')),
                ('is_completed_fact', models.BooleanField(default=False, help_text='Отметка "Да" если работы будут завершены по факту', verbose_name='Окончание работ по факту')),
                ('break_periods', models.JSONField(blank=True, default=list, verbose_name='Перерывы')),
                ('work_object', models.CharField(max_length=255, verbose_name='Объект работ')),
                ('work_type', models.CharField(max_length=255, verbose_name='Вид работ')),
                ('transport_type', models.CharField(max_length=255, verbose_name='Вид транспорта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('responsible_certificate', models.CharField(blank=True, db_index=True, help_text='Только для категории "Подъемные сооружения и такелаж"', max_length=100, null=True, verbose_name='Номер удостоверения ответственного')),
                ('rigger_name', models.CharField(blank=True, help_text='Перечислите через запятую (только для категории "Подъемные сооружения и такелаж")', max_length=255, null=True, verbose_name='ФИО стропольщика')),
                ('rigger_certificates', models.TextField(blank=True, help_text='Перечислите через запятую (только для категории "Подъемные сооружения и такелаж")', null=True, verbose_name='Номера удостоверений стропольщиков')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests', to='core.profile', verbose_name='Подающий заявку (заказчик)')),
                ('equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_requests', to='core.category', verbose_name='Категория техники')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_requests', to='core.organizationlocation', verbose_name='Локация организации')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_requests', to='core.profile', verbose_name='Ответственный')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_requests', to='core.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
