# Generated by Django 5.2.3 on 2025-07-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подачи')),
                ('date_start', models.DateField(db_index=True, verbose_name='Дата начала работ')),
                ('date_end', models.DateField(db_index=True, verbose_name='Дата окончания работ')),
                ('time_start', models.TimeField(verbose_name='Время начала работ')),
                ('time_end', models.TimeField(verbose_name='Время окончания работ')),
                ('is_completed_fact', models.BooleanField(default=False, help_text='Отметка "Да" если работы будут завершены по факту', verbose_name='Окончание работ по факту')),
                ('break_periods', models.JSONField(blank=True, default=list, verbose_name='Перерывы')),
                ('work_object', models.CharField(max_length=255, verbose_name='Объект работ')),
                ('work_type', models.CharField(max_length=255, verbose_name='Вид работ')),
                ('transport_type', models.CharField(max_length=255, verbose_name='Вид транспорта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('responsible_certificate', models.CharField(blank=True, db_index=True, help_text='Только для категории "Подъемные сооружения и такелаж"', max_length=100, null=True, verbose_name='Номер удостоверения ответственного')),
                ('rigger_name', models.CharField(blank=True, help_text='Перечислите через запятую (только для категории "Подъемные сооружения и такелаж")', max_length=255, null=True, verbose_name='ФИО стропольщика')),
                ('rigger_certificates', models.TextField(blank=True, help_text='Перечислите через запятую (только для категории "Подъемные сооружения и такелаж")', null=True, verbose_name='Номера удостоверений стропольщиков')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
