# Generated by Django 5.2.3 on 2025-07-31 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('myrequests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests', to='users.profile', verbose_name='Подающий заявку (заказчик)'),
        ),
        migrations.AddField(
            model_name='request',
            name='equipment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_requests', to='core.category', verbose_name='Категория техники'),
        ),
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_requests', to='core.organizationlocation', verbose_name='Локация организации'),
        ),
        migrations.AddField(
            model_name='request',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_requests', to='users.profile', verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_requests', to='core.status', verbose_name='Статус'),
        ),
    ]
